apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: health-service-cluster-v3
  region: us-east-1
  version: "1.31"

nodeGroups:
  - name: health-service-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 6
    volumeSize: 20
    ssh:
      allow: false
    labels:
      role: worker
    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/health-service-cluster-v3: "owned"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      withAddonPolicies:
        autoScaler: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true
