apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for certificate expiry notifications
    email: admin@codeseeker.dev

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-key

    # HTTP-01 challenge (proves you own the domain)
    solvers:
    - http01:
        ingress:
          class: nginx
